name: DumboServer
server:
  port: 80
########################## MySql配置 ###########################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dumbo_server?characterEncoding=UTF-8&useSSL=false
    #数据库名
    username: dumbo
    #数据库密码
    password: 90977299zhuX
     #MySql驱动名
    driverClassName: com.mysql.jdbc.Driver

######################## MyBatis配置 ##########################
mybatis:
  #entity扫描的包名
  typeAliasesPackage: com.dumbo.server.entity
  #Mapper.xml所在的位置
  mapperLocations: classpath:mapper/*.xml
#  configuration:
#    cache-enabled: true  #开启MyBatis的二级缓存

###################### PageHelper配置 ########################
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

######################### Redis配置 ###########################
redis:
  #数据库索引
  database: 0
  #服务器地址
  host: 127.0.0.1
  #服务器连接端口
  port: 6379
  #连接密码（默认为空）
  password:
  #连接池
  pool:
    # 连接池中的最大空闲连接
    max-idle: 100
    # 连接池中的最小空闲连接
    min-idle: 1
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 1000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    #连接超时时间
    timeout: 5000

######################### Mqtt配置 ###########################
mqtt:
  broker:
    serverUri: tcp://39.106.170.35:61613
    username: admin
    password: password
  inboundclientId: 0
  qos: 1
  completionTimeout: 5000
